# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fdb7d5b2a4d3f05b892c6e8476775407f74ad962e4bb6d11178433203cfaec29119ec61e6d25ce7c951c5e344dda881d0086c58f1c3b7d4fb642c1976f861eb

test:
  secret_key_base: 2d81b800a4f5a8265352e6bc81bc386fc546186ebeb252ed19fd71f75cf5e314fe677cb0490cb7db962f630fdb952ea1d378805cef94e2d417b0ab5fbebe7bb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
