# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9871d60451544b5d9b1ce6746d0bed66bfdf17f60fafabe72f4222fe598d55729d3b2da850e24f4c13a2aec472205056c59231faf7489c0a5ff74586b360e6ef

test:
  secret_key_base: 6f43325db21c27e0ecad28d631289d1e68fdc293a5a17e66fa2ae5b3805a8e4ded99d1867ba87a08b2d1f2a5e34ad2e970c3fa4337b750b2f6694ae5ff1307fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
