# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb44df50aced34f22f49535b693796adf51f4f3c98dc665c2590ccd304eaf99da75609ab20b2be23e5d6d8ee3281c67b5d0a342576520985a41c6fe5e4997b8a

test:
  secret_key_base: 2cb65ab5731ef57ecb52af9485cd6b4d9bfd6549dc52fe1c72202ad0072fd40c2cbef015e0084d7bf58c51eb8de0afb349996a8c613c1def27a7375c96adbaae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
